### ISSUE TITLE
Task Not Created - Windows 7 - WTF?

### ISSUE THREAD

**Issue by stylemessiah** [mkorthof/chrupd#3]
This is starting to get on my tits, you use the word Simple in your script title, but is it...no...

Im running the latest PowerShell  - actually updated it from trying to troubleshoot this

Log follows, please fix ....

Simple Chromium Updater (chrupd.cmd)
------------------------------------ 

New-ScheduledTaskAction : The term 'New-ScheduledTaskAction' is not recognized 
as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is 
correct and try again.
At line:152 char:13
+         $action = New-ScheduledTaskAction -Execute $vbsWrapper -Argum ...
+                   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-ScheduledTaskAction:String) 
    [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
New-ScheduledTaskTrigger : The term 'New-ScheduledTaskTrigger' is not 
recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify 
that the path is correct and try again.
At line:154 char:13
+     $trigger = New-ScheduledTaskTrigger -RandomDelay (New-TimeSpan -H ...
+                ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-ScheduledTaskTrigger:String 
   ) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
& : The term 'Get-ScheduledTask' is not recognized as the name of a cmdlet, 
function, script file, or operable program. Check the spelling of the name, or 
if a path was included, verify that the path is correct and try again.
At line:155 char:13
+     If (-Not (&Get-ScheduledTask -ErrorAction SilentlyContinue -TaskN ...
+                ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-ScheduledTask:String) [], C 
   ommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Get-ScheduledTask : The term 'Get-ScheduledTask' is not recognized as the name 
of a cmdlet, function, script file, or operable program. Check the spelling of 
the name, or if a path was included, verify that the path is correct and try 
again.
At line:161 char:11
+     $task = (Get-ScheduledTask -TaskName "$scriptName")
+              ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-ScheduledTask:String) [], C 
   ommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Task: ""
Description: "", State: .

Logging to: "C:\chrupd-master\\chrupd.log"

Currently installed version: "68.0.3440.106" 

Using the folowing settings:
Checking: "chromium.woolyss.com", Editor: "Nik", Channel: "stable"

[OK] Latest Chromium version already installed

**Comment by mkorthof** [comment]
From a quick google search it seems those cmdlets need Windows 8 or higher (independent of PS version).
Older Windows used different cmdlets, I'll see if I can add support for those too.

As a workaround you can just add a new daily task yourself using the Task Scheduler or schtasks.exe.

For example:
```
schtasks.exe /Create /SC Daily /ST 17:00 /TN "Simple Chromium Updater" /TR "'C:\Example\chrupd.vbs' -scheduler -editor Nik -channel stable"
```
(not tested. for details see schtasks /Create /?)

**Comment by stylemessiah** [comment]
Cheers for the suggestion, but it still fails on a script error in the .vbs. Only setting to run the /cmd file works

I can always use a cmd hiding program i guess until youve updated

Cheers

**Comment by mkorthof** [comment]
Latest version should resolve this (1e7610b)
Could use some more testing tho...

**Comment by stylemessiah** [comment]
i hate to tell you this, but while the scheduled task is created properly, theres no sign of the vbs script anywhere....so it still fails

Windows 7 x64

I deleted the previous folder from c drive, unzipped the latest master and ran the following command line:

`chrupd.cmd -editor Nik -channel dev -crTask`

Command output:

```
``Simple Chromium Updater (chrupd.cmd)
------------------------------------

OS Detected: "Windows 7" (6.1, Workstation)
Task Scheduler Mode: 2, Legacy

Scheduled Task already exists.
Task: "\Simple Chromium Updater"
Description: "Download and install latest Chromium version", State: 3.
```

task created, but no vbs script in folder

**Comment by mkorthof** [comment]
Thanks for testing.
There was a mistake with the vbs variable and path which is fixed now in latest version (b134347).
I tested in win7 vm and task was created OK.

**Comment by stylemessiah** [comment]
Hehe,

All working as expected now. Thanks for the follow up!!

Cheers
